label route01:
    j jdoubt "At first, I admit you had me stumped."
    j "After all, what could a common garden gnome and a bloodied knife possibly have to do with each other, and more importantly, with you?"
    a aneutral "Uh, absolutely nothing because I've never seen either of those before in my life?"
    j jgrim "But then it dawned on me. There could only be one solution."
    j janger "For a man like you, driven by the thrill of the fight, with a callous disregard for life itself, what else could satisfy your sanguine impulses?"
    a adoubt "That's really not a very accurate descri—"
    j janger "This whole time, you've been in charge of a secret criminal cabal! A cabal dedicated to illicit,{w} underground,{w} extremely lethal{w} gnome blood sports."
    show mono afear
    ""
    j jdoubt "Your silence says it all."
    j "Trapping innocent gnomes in cages . . . {w}starving them to stoke their fury . . . {w}arming them with kitchen knives . . ."
    j janger "You disgust me."
    j "What a sick, sick world we live in."
    a adoubt "Literally none of that was remotely true."
    a afear "It doesn't even make any sense!"
    j janger "Nothing in this twisted society makes sense, Badmann."
    j "The blood . . . {w}the greed . . . {w}the insatiable hunger . . ."
    j "All of it swirling together in the gutter of depravity."
    j jgrim "It's too much for one kid detective to solve."
    j jsmug "Even for me, Jam, the world's greatest kid detective between the ages of 4 and 17 in the western half of Linn County."
    j jdoubt "Now if you'll excuse me, I'm gonna go home, have some deep thoughts about the evils of human nature, and write some poetry about it."
    j "This sinful earth is crying soft,\n{w}its sobbing drowned by cries of strife.\n{w}Who can bear Hope's torch aloft,\n{w}above the waves of ruthless life?"
    j jneutral "Mmm, yeah, that's a good start."
    show mono empty
    alt "Jam departs."
    ">>>"
    a afear "Kid?"
    a aalarm "Wait! You can't just leave me here!"
    a "Kid! Come back!"
    show mono 01 with dissolve
    alt "A short, jolly figure appears in the open doorway, carrying a knife."
    a ". . . Kid?"
    jump endcard

label route02:
    j "I knew exactly what was going on as soon as I found the money under the couch."
    a afear "Wait, there was money down there?"
    a adoubt "Damn . . . I only checked between the cushions."
    j jdoubt "And you know what they say: where there's smoke, follow the money."
    j janger "So I followed that money, all the way back to the filthy heart of the criminal enterprise that spawned it."
    j jgrim "And that heart is you, Alexandre V. Badmann."
    j janger "Or should I call you . . . {w}Lucky Benny's House of Gnomes?"
    a afear "Wait, what?"
    j janger "Surprised I caught on so quick? Well, maybe next time, you should remember who you're dealing with!"
    j jsmug "Specifically, you're dealing with Jam, the world's greatest kid detective between the ages of 4 and 17 in the western half of Linn County."
    j jdoubt "I know all about the eBay listings for the stolen vintage garden gnomes that you're scalping!"
    j jneutral "Mostly because I googled them on my phone like six minutes ago, but I mean, still."
    j jdoubt "You've been using this abandoned mansion as your base of operations for fencing lifted lawn leprechauns!"
    a adoubt "I realize it's possible that you've, I don't know, forgotten my first name over the span of the last fifteen seconds, but my name is Alexandre, not Benny."
    a aneutral "Hell, I don't even own a computer!"
    j jgrim "I'm sure something like that wouldn't even be a trifle for a criminal mastermind like yourself."
    j jdoubt "But either way, I'm shutting your business down for good."
    j "Here's some customer feedback for you, Badmann:"
    j janger "0/5; wouldn't shop again."
    j "Later."
    show mono empty
    alt "Jam departs."
    ">>>"
    a afear "Kid? Wait, kid!"
    a "Aren't you forgetting something? Something like untying me?"
    a aalarm "Don't just leave! I don't want to die!"
    a "For god's sake, at least take me with you to the police station!"
    a afear ". . ."
    a adoubt "Ugh. Well, at least I didn't get left totally in the lurch."
    a "If I break the gnome with my feet, maybe I could cut myself free with one of the shards. Just gotta—"
    a aalarm "—Wait, where'd it go?"
    show mono 02
    alt "The garden gnome pops up over Alexandre's shoulder."
    a "I swear, it was here just a second ago . . ."
    jump endcard

label route03:
    j "I present my first exhibit: this garden gnome."
    a adoubt "Oh, yeah, that's a criminal gnome if I ever saw one."
    j jgrim "You may laugh, but your joke couldn't be further from being not close to the truth."
    j jsurprise "Allow me to present exhibit number two: a human jawbone!"
    a afear "Uh."
    a "Kid, where exactly did you find that?"
    j jdoubt "Why should I bother telling you? I'm sure you know exactly where you left it . . ."
    j janger ". . . after you were finished sacrificing the rest of the body to the gnome demons!"
    a aneutral ". . . gnome . . . {w}demons?"
    j jdoubt "The demons spoken of in that fabled grimoire of foul magic, the Necrognomicon."
    j "The demons that you think have been communing with you through the gnome statue."
    j janger "Why else would you lock the gnome away in a secret compartment?"
    j jgrim "That summoning circle in the bedroom . . . The, uh, whatever that godawful thing was in the lounge . . ."
    j janger "They're all part of your vile human sacrifice rituals, aren't they?"
    a aalarm "Wait, you mean you saw the thing in the lounge too?"
    j jgrim "I mean, it's kinda hard not to."
    a aalarm "That's the thing I was trying to warn you about! It looks like it's taxidermied, but I swear, when I was up there, I saw it move!"
    j jdoubt "Oh, I'm sure you did . . ."
    j janger ". . . while you were hiding inside it, murdering your innocent victims to appease the gnome demons!"
    j "But this sick charade ends here."
    j jdoubt "The gnome demons aren't real, Badmann. The only thing you've been appeasing is your own appetite for carnage!"
    j "I didn't want to do this, but it's the only way to bring you back to your senses!"
    ">>> The garden gnome shatters on the ground with a resounding crack."
    j jgrim "There. It's finished."
    j janger "Take some time to think about what you've done, murderer."
    j "I hope you're sorry."
    show mono empty
    alt "Jam departs."
    ">>>"
    a afear "Wait, you've got it all wrong! This is exactly what I was trying to warn you about!"
    a aalarm "Kid, don't go! I don't want to get eaten by worms!"
    a "Kid! Please!"
    show mono 03 with dissolve
    alt "Something begins to wriggle among the shards of the broken garden gnome."
    a "Kiiiiiiid!"
    jump endcard

label route04:
    j jsurprise "Behold, the evidence!"
    j janger "Anything to say for yourself, criminal?"
    a adoubt ". . . A fish and a garden gnome."
    a aneutral "That's, uh, compelling."
    j janger ". . ."
    j jgrim "Ugh, alright, fine."
    j "I tried really hard to figure out how those two fit together, but I just couldn't think of anything."
    j jdoubt "Honestly, I was hoping you'd just confess to whatever it was you did when I showed them to you."
    j jthink "I dunno, like, maybe you were running a blackmarket Red Lobster/Joann Crafts knock-off? Kinda like those places that are somehow both a Taco Bell and a KFC at the same time?"
    a adoubt "That's maybe the worst idea for a business that I've ever heard."
    j janger "Not like you have to rub it in!"
    a afear "Okay, okay, sorry."
    a agrin "Anyway, we're both on the same page now, right? You were wrong about me, this house is way too spooky, and we both need to get the hell out?"
    j jdoubt "Who said I was wrong? You did do something here; I just haven't figured it out yet."
    a adoubt "Seriously, kid? Can't you just admit defeat for once?"
    j janger "Hmph! If that's how it's going to be, maybe I'll just leave you here and you can figure out how to escape, since obviously you're just so much smarter than me."
    a afear "Hold on, that's not what I meant!"
    a "Don't go! At least untie me first!"
    j janger "Untie yourself. I'm leaving."
    a afear "Wait, kid!"
    a agrin "Wait, uh . . . Jam, the world's greatest kid detective between the ages of 4 and 14 in the western half of Linn County?"
    j jalarm "Between 4 and 17!"
    show mono empty
    alt "Jam departs."
    ">>>"
    a aalarm "oh god i'm going to die here aren't i"
    a afear "Alright, easy there, Alexandre. You can do this."
    a "Jam left the door open, so if I just wiggle this chair over to the exit . . ."
    show mono 04 with dissolve
    alt "As Alexandre scoots towards freedom, a writhing figure approaches from the shadows."
    a ". . . I'm sure I'll make it out of here somehow."
    jump endcard

label route05:
    j "Now, you may be wondering, what's the connection between a seemingly innocent garden gnome and this incomprehensible post-it?"
    a adoubt "I honestly couldn't be any less concerned about that than I am right now."
    a aneutral "What I actually want to know is are you going to untie me or wh—"
    j jsmug "Well, allow me to enlighten you!"
    a adoubt ". . . Oh great, here we go."
    j jdoubt "The note reads: \'Iron Snail Authorization\'."
    j "Snails are mollusks, and you know what else are mollusks? Clams! And 'clams' is slang for American dollars!"
    j "I'm sure you can see where this is going."
    a aneutral "Do you even know where this is going?"
    j jdoubt "It's all going back to you, Badmann!"
    j "Iron is a metal, and American dollars are made using metal presses, through the authorization of the US Mint. And you know what's closely related to mint?"
    j janger "That's right: catnip! Which is a drug! For cats! Which is exactly what you're smuggling in these garden gnomes!"
    a afear "Wait, am I smuggling catnip or cats?"
    j janger "No! I mean neither! Well, okay, I won't rule either of them out, but I'm talking about drugs here!"
    j jdoubt "And not the soft stuff like whatever my brother's been vaping out behind the shed. I'm talking hard drugs."
    j "Crack; snow; candy; powder; dust; blow—heck, even coke, just to name a few of them."
    j "Need I continue?"
    a aneutral "You really don't."
    j janger "But this is the end of the line for you, Badmann."
    j jdoubt "You know what they say about people who smuggle drugs in garden gnomes, don't you?"
    a adoubt "No."
    j janger "Here's what they say:{w} crime doesn't pay."
    a adoubt "Oh for fu—"
    a aneutral "Listen, kid, this has gone on long enough."
    a "I don't care about the stupid gnome! But if you and me stay in this house even a minute longer, we're likely to get eaten by worms or a demon or something."
    a adoubt "So would you just untie me already?"
    j jdoubt "Not until I've heard you confess with my own ears."
    a adoubt "Ugh, fine."
    a aneutral "I did the gnome crime. Happy now?"
    j jneutral "Yep!"
    a agrin "So you'll untie me?"
    j jneutral "Nope!"
    a adoubt "w{w}h{w}y"
    j janger "You know what else they say? Don't do the gnome crime if you can't do the gnome time."
    j "I'll let you mull that one over in the slammer."
    j jdoubt "And by the slammer I mean this room, where I'm leaving you."
    show mono empty
    alt "Jam departs."
    ">>>"
    a adoubt "Aaaand the kid's gone."
    a afear "Okay, Alexandre, let's take this slow and calm. You're gonna make it out of here alive."
    a "You just need to smash the gnome with your feet, grab one of the shards, and cut yourself free before whatever that thing is comes downstairs."
    a agrin "It's fine! Totally fine!"
    show mono 05 with dissolve
    alt "The gnome stares up at Alexandre with eyes full of writhing worms."
    a "I'm sure I've got plenty of time!"
    jump endcard

label route06:
    j jgrim "I can't believe I didn't catch on to it earlier."
    j jdoubt "You've been doing it under my nose this whole time!"
    j jalarm "And I am so,{w} so{w} sorry!"
    a afear "Wait, what?"
    j jalarm "You've been selling your organs online just to make ends meet, and I never even noticed!"
    j jgrim "I thought you were just stealing for fun, but really you were doing it to feed your family!"
    j "Every time I caught you, every time you pleaded for me to let you go . . ."
    j "I kept telling myself it was all for the sake of justice, but I was too blind to see that the real injustice was financial inequality all along."
    j jdoubt "Words can't express my shame. I feel like I'm Inspector Valjert from that Hugh Jackman movie."
    j "In my pursuit of an incorruptible ideal, I lost sight of what really matters: truth."
    a aneutral "Uh, can we rewind for a moment? How exactly did you jump to that conclusion from a jawbone and a pile of cash?"
    j jneutral "It was easy, once I saw how all the pieces connect."
    j jthink "If my mastery of forensic anatomy serves, that jawbone could only have come from a human—specifically, an adult human between the ages of 20 and 200."
    j "Curious, isn't it, that such a jawbone would appear in the same building as the only human adult I know who's willing to speak to me for more than two minutes at a time?"
    a afear "Hold up—I don't want to pry, kid, but, uh, aren't you in school? Don't you have teachers?"
    a "Hell, do you even have legal guardians?"
    j jthink "Yes, it was curious indeed, and that's when I remembered something important."
    j "I had read that people will sometimes sell powdered rhino bones on the internet as a kind of medicine, often for a very high price."
    j jgrim "If that was so, then why not human bones as well? And thus, it was then that I realized this was no crime at all!"
    j jsurprise "In reality, you had surgically extracted your own jawbone to grind up and sell as a black market aphrodisiac!"
    show mono afear
    alt "Alexandre is dumbfounded."
    ""
    j jalarm "Ah, my apologies. I didn't mean to make your jaw drop. I realize it must have only very recently regenerated, after all."
    show mono afear
    alt "Alexandre gawks in stunned silence."
    ""
    j jgrim "At any rate, I'm truly sorry for everything I've done till now."
    j jsurprise "From here on out, I swear I'll do my best to support you, not as archnemeses, but as friends!"
    a agrin "Thanks?"
    j jneutral "Please, don't mention it."
    j "Now, let's get you untied so I can give you back your jawbone and your pile of money!"
    a agrin "Seriously? Wow, that's incredibly gul—waitimean incredibly helpful of you!"
    j jneutral "It's the least I can do, if I want to start making things right."
    show mono 06 with dissolve
    alt "Jam stands beside Alexandre. They're both grinning, and so is the horse-masked figure looming behind them."
    j "And besides, who doesn't like a happy ending?"
    jump endcard

label route07:
    j jdoubt "Any of this look familiar?"
    a aneutral "Would you even listen if I said no?"
    j jdoubt "This is the fish from the kitchen fridge, and the human jawbone that was left in bathroom trash can."
    a afear "Wait—human jawbone? In a trash can?"
    a aalarm "And you just picked it up and threw it in your backpack?"
    j jgrim "I uncovered it while I was searching for clues—exactly as you planned, no doubt."
    a afear "You seriously believe I just left someone's jaw in the garbage? Do you think I'm some kind of serial killer?"
    j janger "You'd like me to think that, wouldn't you?"
    a aalarm "No! No I would not!"
    j jdoubt "Trying to pull the old reverse psychology, eh? Too bad! You can't fool me that easy!"
    j jsmug "It's impossible to trick Jam, the world's greatest kid detective between the ages of 4 and 17 in the western half of Linn County."
    j jdoubt "Everything was staged to make it look like these were important clues that would lead me to the answers I sought, but that was an elaborate ruse!"
    j "This discarded mandible . . . this crimson fish . . ."
    j "These weren't clues at all! Their true nature becomes apparent when you combine them."
    j "In actuality, this was . . ."
    j jgrim ". . . a jaw-dropping red herring!"
    a adoubt ". . ."
    a "I'm going to ignore the pun for now."
    a aneutral "More importantly, are you actually agreeing that I didn't commit any crimes here?"
    j jgrim "It may be true that nothing you've done here was illegal . . ."
    j janger ". . . but you did try to trick me, waste my time, and tarnish my reputation as Jam, the world's greatest kid de—"
    a adoubt "—aaaand I'm gonna stop you right there."
    a aneutral "None of that was me either."
    j janger "A likely story! If you didn't leave those red herrings lying around, then who did? It's not like anyone else is living here."
    a aneutral "Actually, about that."
    a afear "There's something you need to know, kid."
    a "Upstairs, in the lounge, there's this godawful monster, and I'm pretty sure it's—"
    j jneutral "Oh yeah, that."
    j "I put a horse mask on it."
    a afear "You what?"
    j jneutral "It's still kinda freaky, though. Like, trust me, I'm pretty sure I'm gonna have nightmares about that mask for the better part of my adult life."
    j "Anyway, since there's nothing for me to actually do here, I'm gonna go scrub those images from my brain with some ice cream and binge-television."
    j jgrim "Later, loser. Try coming up with an actual crime next time."
    show mono empty
    alt "Jam departs."
    ">>>"
    a aalarm "Kid, wait! At least untie me first!"
    a "Come back!"
    a ". . ."
    a afear "Ha, ha, well, it's just you now, Alex."
    a "Deep breaths, deep breaths. You're gonna get out of here alive. Nothing to be afraid of!"
    show mono 07 with dissolve
    alt "From somewhere in the distance comes a squelching sound, like a set of upsettingly detailed rubber teeth chomping down on a dead fish."
    a "I mean, what could be so awful about a horse mask?"
    jump endcard

label route08:
    j jgrim "The note was the first piece of evidence I uncovered."
    j "\'Iron Snail Authorization\' sounds cryptic at first glance, but in actuality, its meaning is quite simple!"
    j jthink "An iron snail . . . Metal on the outside, but soft on the inside. In other words . . ."
    j jsurprise "A tooth with a crown!"
    a aneutral "That seems like a bit of a leap."
    j jdoubt "Perhaps, if I hadn't discovered my second piece of evidence: this human jawbone!"
    a afear "That's . . . not real, is it?"
    j jneutral "I mean, it smells kinda rotten, so . . . yeah?"
    j jgrim "Anyway, once I had that, I knew exactly what you were up to."
    j jthink "This whole time . . . {w}unbeknownst to anyone . . . {w}hiding in the shadows . . ."
    j jsurprise ". . . you've been studying to become a dentist!"
    a afear "I have?"
    j jalarm "Of course you have! It's the only possible solution!"
    j jneutral "And you know, I'm actually pretty proud of you."
    j "It takes a lot of courage and determination to break from your criminal ways and turn your life around."
    j jsmug "I've totally got your back on this one!"
    a agrin "Oh, that's . . . that's really pretty nice of you!"
    a adoubt ". . . totally wrong, but nice."
    j jneutral "Did you say something?"
    a agrin "Nope! Just thinking to myself what a great pal you are, Jam!"
    a "Now how about you untie me so I can get back to studying? Got a big dentist exam coming up, you know."
    j jneutral "Sure thing, Alexandre, ol' pal! Or maybe even . . ."
    j jsmug ". . . Palexandre?"
    show mono adoubt
    alt "Alexandre shoots Jam a dirty look."
    ""
    j jgrim "Okay, fine, maybe not that one."
    j jneutral "Anyway, let me just find my pocketknife and I'll get you out of there."
    j jthink "Turns out putting like fifty knots in a rope is pretty straightforward, but untying those knots is a real pain!"
    show mono 08 with dissolve
    alt "Something is gleaming in the shadows behind Alexandre. It looks uncannily like a set of bright, shiny, rubber horse teeth."
    j "Funny how that works, isn't it?"
    jump endcard

label route09:
    j jsurprise "Behold, evidence number one: a human jawbone!"
    a afear "You mean that was just lying around this place?"
    j jgrim "But of course. Why should it be surprising to find human remains . . ."
    j jdoubt ". . . at the scene of a murder?"
    a afear "Murder?"
    a "Are you serious, kid?"
    j janger "Deathly serious. For you see, my second piece of evidence . . ."
    j jdoubt ". . . is this bloodstained knife!"
    a afear "Kid, please tell me that's just ketchup."
    j jgrim "I'm afraid not; I'd know the scent of blood anywhere."
    j jdoubt "Ah, the murder weapon and the remains of the victim, together under the same roof."
    j jgrim "All that's missing . . ."
    j janger ". . . is the murderer."
    a afear "Okay, listen, I realize this looks bad, but I swear I never killed anyone!"
    a aalarm "You've got to believe me!"
    j jneutral "Oh, I believe you, Badmann. How could I not?"
    j jdoubt "After all, the actual killer . . ."
    j jmurder ". . . was me!"
    show mono aalarm
    ""
    j jmurder "Hahahahahahahahahahahahaha!"
    j "You're such a naive fool, Badmann. And that's what made you the perfect prey."
    j "All these years spent as nemeses; our endless charades of cat and mouse—"
    alt "Jam draws the revolver on Alexandre."
    j jgun2 "All mere warmups for the most dangerous game."
    j "And when I'm done here, and it's your jaw casually tossed aside like a wishbone from a bucket of KFC . . ."
    j jmurder ". . . not one soul will notice that you're gone, and not one will suspect a thing."
    j "It will be, as they say, the perfect crime."
    a afear "Please, kid! You don't have to do this!"
    a "Just let me go! I won't tell anyone!"
    a aalarm "I don't want to die!"
    j jmurder "That's what they all say, Badmann. That's what they all say."
    j jgun2 "Now then . . . {w}It's time to say good-bye, old friend."
    j ".{w} .{w} ."
    j jneutral "bang"
    show mono aalarm
    alt "Alexandre braces for the gunshot."
    ""
    show mono afear
    alt "It doesn't come."
    ""
    a adoubt "Wait, did you just say the word 'bang'?"
    j jsmug "Ha! Oh man, I can't believe you fell for it!"
    j jterror "\'oOwOo the real murderer was me, super spooky\'"
    j jsmug "As if!"
    j jgrim "You know, for an intermunicipal criminal genius, you're hecka gullible."
    a afear ". . ."
    a adoubt "You little shit."
    j jsmug "What's the matter, Badmann? Embarrassed?"
    j "If only you could have seen the look on your face!"
    j jneutral "Fortunately, I can see it whenever I want because I made sure to record the whole thing on my phone."
    j "Anyway, I'm gonna go home and upload that to youtube."
    j jsmug "If it goes viral, you can have like 10\% of the ad money."
    j jneutral "Later!"
    show mono empty
    alt "Jam departs."
    ">>>"
    a aneutral "Kid! Get back here!"
    a adoubt "Untie me, you miserable little gremlin!"
    a aneutral ". . . ugh, looks like I'm all alone."
    a "Whatever, I can get out of this one myself."
    a "I've got a knife now; that's something, at least."
    a afear "Wait, where's the knife?"
    show mono 09 with dissolve
    alt "The knife emerges from the shadows behind Alexandre, clasped in an unknown hand."
    a "I could swear I saw it just a second ago . . ."
    jump endcard

label route10:
    j jdoubt "I have to say, this case was a tricky one."
    j jthink "A strange fish and an encrypted message . . ."
    j "For a lesser detective, one less worldly and rigorously well versed in subjects ranging from geography to social studies, perhaps it would have even been insurmountable."
    j jsmug "But not for me, Jam, the world's greatest kid detective between the ages of 4 and 17 in the western half of Linn County!"
    j "It took all my wits to crack this one, but once I saw the connection, the answer was as clear as obsidian."
    a adoubt ". . . Kid, have you ever actually, like, been outside Linn County?"
    j jdoubt "Curious that you should mention travel, Badmann! Most curious indeed!"
    j janger "also just for the record, i did in fact visit portland for a raffi concert when i was four, so you can stop treating me like some ignorant child any time now"
    j jneutral "Ahem. Anyway."
    j jdoubt "My first hint was in the initials of the note."
    j "'Iron Snail Authorization', or ISA. What else could that stand for, you ask? Well, I'll tell you!"
    j janger "International{w} Secret{w} Assassination!"
    j "Not content to be a mere intermunicipal criminal genius, you had set your sights on a much grander prize!"
    j "Cold-blooded murder in a foreign land!"
    a adoubt ". . . Do I look like a cold-blooded murderer to you?"
    j janger "Looks can be deceiving, Badmann! That's the first rule of detective-ing."
    j jdoubt "Regardless, it wasn't enough to merely uncover the nature of your plot."
    j "I had to identify your intended victim and means of assassination."
    j jdoubt "Fortunately, you left me with a second valuable clue hidden in the note."
    j jthink "Why write 'snail', and not, for instance, 'sarrusophone'?"
    a adoubt ". . . Because no one knows what the hell a sarrusophone is?"
    j jsurprise "But think! Where are snails most commonly eaten?"
    j janger "That's right: France!"
    j jneutral "Of course, we both know you're too broke to fly to France, so I had to look elsewhere."
    a aneutral "Wow, okay, that was totally unnecessary."
    j jdoubt "In France, the national language is French, but do you know where else they speak French?"
    j janger "Canada, that's where!"
    j jgrim "A vast, almost entirely uninhabited wilderness, full of extremely polite, internationally famous musicians who don't lock their doors at night, a mere eight hours away by car!"
    j "I couldn't devise a more perfect venue for your vile schemes even if I made it up entirely on the spot."
    a adoubt "You're pretty much there already, kid."
    j jdoubt "But how, then, to commit this murder?"
    j jthink "A wayward hockey puck? Locking your victim in a cage with a starved beaver?"
    j jgrim "No, such means are too inelegant for someone like yourself, and thus we come to the fish."
    j janger "To kill a francophone, only one tool is suitable:"
    j jdoubt "Poisson."
    a afear ". . ."
    a ". . . wait, what?"
    j jgrim "It means 'fish' in French."
    a adoubt "Oh."
    j jneutral "Anyway, just in case you're still planning to go ahead with the whole fishmurder roadtrip thing, I went ahead and took the precaution of slashing your tires."
    j "My work here is pretty much done."
    a afear "Wait, you did what?"
    j jneutral "Later!—or rather, hasta la vista!"
    j "That means 'later' in French."
    show mono empty
    alt "Jam departs."
    ">>>"
    a adoubt ". . . I'm pretty sure that's Italian."
    a aneutral "Ugh, what a mess. Stuck in a haunted house, tied to a chair, and now I need to buy new tires."
    a "At least it can't get any worse?"
    a agrin "Still, the kid was right about one thing."
    show mono 10 with dissolve
    alt "As Alexandre contemplates the great north, he fails to notice the footsteps approaching him from behind."
    a "A nice, long vacation in Canada sounds pretty appealing right now."
    jump endcard

label route11:
    j jdoubt "They seem so inconspicuous at first, don't they? A fish and some cash."
    j jgrim "You might even be tempted to dismiss them as irrelevant to the case at hand."
    j janger "But you'd be wrong! WRONG!"
    j "These seemingly random items are actually the crux of an international criminal conspiracy, and you, Alexandre V. Badmann, are the ringleader!"
    a aneutral "Kid, I've never even left the west coast."
    j jdoubt "And why would you need to, when you have peons scattered across the globe, doing your nefarious bidding?"
    j jgrim "This quaint life you lead in Linn County as a totally unsuccessful failure of a cat burglar, wasting away your fading youth quarreling with a schoolkid . . ."
    j janger "It's all just an ingenious disguise to throw the feds off your trail! But I'd expect no less from a peerless villain such as yourself."
    a adoubt ". . . Wow, even when you're complimenting me, you still somehow manage to make me feel like shit."
    a aneutral "And more importantly, you haven't even told me what I'm allegedly doing with this global crime syndicate!"
    j jdoubt "Oh, but isn't it obvious? The fish alone tells you everything you need to know."
    j jthink "At first, I thought perhaps it was a member of the genus Clupea; some kind of herring or whatever."
    j janger "But only an amateur jumps to conclusions!"
    j jdoubt "After countless painstaking hours of thorough research and analysis, I've come to a very different answer!"
    a adoubt "We've been in this house for like forty-five minutes, tops."
    j janger "Okay, fine, maybe it was more like three minutes on Wikipedia, but that's beside the point!"
    j "This is no common herring, but a critically endangered red handfish!"
    a adoubt "Don't handfish have, you know, hand-looking fins? The fins on this one look pretty normal to me."
    j jdoubt "I'm sure it would have had hand-fins . . ."
    j janger ". . . if you hadn't harvested them to sell on the black market as a delicacy!"
    j "For decades now, you've been poaching endangered aquatic wildlife across the globe, all to fill the bellies of corrupt oligarchs!"
    j jdoubt "Handfish fins . . . {w}turtle fins . . . {w}shark fins . . ."
    j jgrim "How many have died by your hands? How many innocent animals have you drowned in your sanguinous soup of sin?"
    j janger "But I say no more! Your trail of blood ends here, Badmann."
    j jdoubt "For your diabolical poaching ring, I'm afraid that this is . . ."
    j jgrim ". . . la fin."
    a adoubt "Wow, look at young James Bond over here dropping one-liners like first-period electives."
    a aneutral "How many times do I have to tell you? I didn't do jack, and every minute you waste on this farce is another minute closer to us getting murdered by the monster upstairs!"
    j jdoubt "What, the thing with all the eyes? I'm pretty sure it's just a taxidermied model."
    j janger "Another now-extinct species cut down by your gang of poachers, no doubt."
    a aalarm "Does that thing look like an endangered species to you?"
    j jneutral "Are horses endangered? I don't really remember."
    a afear "Wait, what? Horses?"
    j jneutral "Anyway, that's pretty much that."
    j jthink "I brought out the evidence, dropped the accusation, had a couple dramatic twists, and even made a plot-relevant pun, so that covers all my usual bases."
    j jsmug "See ya next week! Maybe next time you'll come up with a better crime!"
    show mono empty
    alt "Jam departs."
    ">>>"
    a afear "Wait, you can't leave yet! You still have to untie me!"
    a aalarm "You never even told me what you meant about the horses!"
    a aneutral ". . . Ugh, whatever. Guess I'll have to get out of this myself."
    a "A loyal army of criminal fishmongers sure would come in handy right about now."
    a adoubt "Not like that's gonna happen anytime soon."
    show mono 11 with dissolve
    alt "As Alexandre mutters to himself, a multitude of gray worms begin slithering out from the fish's mouth."
    a "Hell, I don't even like fish."
    jump endcard

label route12:
    j jdoubt "A herring and a thoroughly used knife. Suspicious, no?"
    j jsurprise "Or so I thought, but in actuality, the truth was even stranger than I could have guessed!"
    j jthink "Consider the herring. A common baitfish, yes, but also an international culinary staple!"
    j jgrim "Yet that alone was not enough for me to narrow the scope of what was afoot here."
    j "For that, I needed to look at the utensils at hand."
    j jthink "I found no evidence of any intent to cook this herring, and no pertinent kitchen implements, save for this knife."
    j jdoubt "How could one serve herring raw, and with only a knife?"
    j "It was then that I recalled something one of the weebs from the school anime club had told me."
    j jsurprise "In Japan, raw fish is known as sashimi, and nishin—that is, herring served with roe—is a particular delicacy."
    j "Suddenly, it was all clear to me!"
    j janger "Alexandre V. Badmann, you've been conducting your business in the shadows long enough!"
    j "It's time your deeds were finally revealed!"
    j "Yes, it's time that the world knows that you are, in fact . . ."
    j jneutral ". . . an aspiring sushi chef!"
    a afear "I'm doing what now?"
    j jgrim "In hindsight, it makes perfect sense. After so many years struggling as a low-level criminal, you wanted to make a clean break from your sordid past."
    j jthink "You wanted to make a living through honest work—a fresh start. And what could be fresher than raw fish?"
    j "Yet you knew that your underworld associates would frown on your epicurian explorations, so you hid yourself away in this abandoned mansion to train."
    j jdoubt "The blood on the knife is none other than your own, spilled by mistake during a particularly intense prep session!"
    j jsurprise "This was no crime at all—this was passion!"
    a afear ". . ."
    a "Okay, yes, sure. That's exactly what's going on here."
    j jneutral "You know, this is some pretty inspiring stuff. Like, you could make a documentary out of this."
    a aneutral "That's great, kid."
    a agrin "Now please untie me."
    j jneutral "Of course! Who am I to stand between a man and his dream?"
    j jgrim "It's gonna be a minute, though. I tied these knots hecka tight, and my hands are super slimy from carrying that herring around."
    a aneutral "You do realize you have a knife, right?"
    j jneutral "Yeah, but I don't want to turn you into sashimi by mistake."
    a agrin "Alright, that's fair enough."
    show mono 12 with dissolve
    alt "Unseen by Jam or Alexandre, a hand reaches out for the cast-aside fish."
    a "I'd probably taste terrible anyway."
    jump endcard

label route13:
    j jdoubt "Cash, blood, and a knife—a classic combination, no?"
    j "A combination that, at a glance, can signify only one thing:"
    j janger "Murder."
    a aalarm "Kid, I swear to god I'm not a murderer! I've never even seen that knife before!"
    j jgrim "One of those two statements may be true, but the other is without a doubt a lie."
    j jdoubt "To determine which is which, we must first take stock of our subconscious biases."
    j jthink "If not murder or mugging, are there other ways one could make money with a knife?"
    j "Knife-throwing at a circus, perhaps, but you're no clown, Badmann . . ."
    j janger ". . . you just dress like one."
    a afear "wait what's wrong with my turtleneck"
    j jgrim "No, in these modern times, classical detective thinking is too old-fashioned."
    j "When I realized this, I knew what I had to do . . ."
    j jneutral ". . . which admittedly was waste like fifteen minutes on youtube watching some dude breaking raw spaghetti with his forehead . . ."
    j jdoubt ". . . but what an enlightening fifteen minutes it was!"
    j "Online, there's an audience for anything, even mildly fetishistic pasta demolition videos."
    j janger "And where there's an audience, there's advertising money!"
    j "So while the average armchair detective might look at the evidence and see murder as the only option, I know what's really going on here!"
    j jdoubt "With this abandoned mansion as your hideout, you've been making a little side-money . . ."
    j janger ". . . by making ASMR videos of yourself cutting random objects in slow motion with this knife taped to your chin!"
    a adoubt ". . ."
    j jdoubt "Has my investigative prowess left you too stunned for words? I'll take that as your confession, Badmann."
    j jsmug "Yet another case solved by yours truly: Jam, the world's greatest kid detective between the ages of 4 and 17 in the western half of Linn County!"
    a adoubt "Wait, hold up, kid. Let's just assume for a moment you're right about all this."
    a aneutral "Are you basically saying that I didn't do anything illegal?"
    j jneutral "I mean, no, nothing technically illegal."
    a aneutral "So you agree that I'm innocent!"
    j jdoubt "Yeah? I guess?"
    a agrin "Great! Then you're gonna untie me, right?"
    j jgrim ". . . Eh."
    j "I said it wasn't illegal, but it's still kinda weird, you know."
    j jdoubt "You can keep the knife and the cash, but I'm done here."
    j jneutral "I think I'm gonna go home and watch more of the spaghetti guy."
    j "There's something weirdly hypnotic about the way the noodles crack across his forehead."
    show mono empty
    alt "Jam departs."
    ">>>"
    a adoubt "Well, that was definitely more information than I ever wanted to know."
    a aneutral "Could have gone worse, though. I've at least got the knife, and I somehow even made a little money."
    a "Just gotta figure out to cut the ropes with my hands tied behind my back . . ."
    show mono 13 with dissolve
    a "Honestly, how hard could it be?"
    alt "For more videos of burglars getting devoured by demons, make sure to like and subscribe."
    jump endcard

label route14:
    j jgrim "A strange collection of evidence, isn't it?"
    j jdoubt "A note, shrouded in secrecy . . . {w}a knife, steeped in blood . . . {w}a mansion, lost to ruin . . ."
    a adoubt "Not sure I'd call a 1B1B a mansion, but—"
    j janger "—but this evidence is all I need to crack this case wide open!"
    j jdoubt "Yes, this case of violence; passion; romance . . ."
    j jalarm ". . . the Confounding Case of the Clowns and the Craniums!"
    a aneutral "The what-nows?"
    j janger "Spare me the feigned ignorance, Badmann. We both know you're not as completely dim-witted as you look—"
    a afear "Uh, thanks?"
    a adoubt "Wait, or was that an insult . . ."
    j janger "—but you are a bonehead! Or should I say . . ."
    j jdoubt ". . . a skull from the Cranium Gang?"
    j jgrim "I knew what was up as soon as I saw the paintings in the parlor and bedroom."
    j jthink "This mansion may look totally trashed and unwanted . . ."
    j jsurprise ". . . but it's actually the staging grounds for the bitter, bloodsoaked turf war between the rival gangs, the Clowns and the Craniums!"
    j jdoubt "The skull and clown paintings are the gangs' way of marking their territory, like graffiti but infinitely less practical."
    j jgrim "The second floor is Clown turf, while the Craniums rule the ground floor."
    j jthink "From the fact that I found you in the living room, it was simple to deduce that your loyalty lies with the Craniums. Am I wrong?"
    a aneutral "I mean, yes?"
    a adoubt ". . . even if I do hate clowns."
    j jsurprise "Aha! So the truth comes out!"
    j jdoubt "And with that, everything else falls tidily into place."
    j jgrim "Tell me, Badmann: in a tussle, what's a gangster's second-most-deadly weapon?"
    a adoubt "Hmmm . . . I guess a gun would be number one, so . . ."
    a aneutral ". . . a knife?"
    j jgrim "Precisely. And what a coincidence that I should find just such a weapon locked away deep within Clown territory!"
    j jdoubt "One might assume that you had hidden armaments there to later access when the Craniums stormed the second floor, but I don't think it's that simple."
    j jsurprise "The knife was bloodied when I found it. In other words, this was an implement not of future violence, but of violence past!"
    j jdoubt "A memento of a fallen comrade. Or perhaps even . . ."
    j janger ". . . a lover?"
    a aneutral "Kid, you know I'm already married, right?"
    j jdoubt "But your lover couldn't have been a fellow Cranium. If that had been the case, why then would the knife be on the second floor?"
    j jgrim "No, Badmann . . . {w}you fell in love with a Clown, didn't you?"
    show mono adoubt
    alt "Alexandre is too stunned to respond."
    ""
    j jgrim "A forbidden love. Starcrossed, even."
    j jneutral "Like Tony and Maria from Shakespeare's timeless masterpiece, A Midsummer Night's Dream."
    j jgrim "And when your lover, like Tony, perished in a brutal knifefight in this very house, you swore revenge."
    j jdoubt "A revenge no less than the total annihilation of all the remaining Clown gang!"
    j jthink "This note . . . 'Iron Snail Authorization' . . ."
    j "Here's another question, Badmann: what is a snail?"
    a aneutral "Uh, a mollusk?"
    j jgrim "Okay, yes, but I was kinda hoping you'd give a less accurate answer."
    a aneutral "A slug in a shell?"
    j janger "Exactly! And so we come to the truth of the iron snail!"
    j jsurprise "A slug in a metal shell!"
    a afear "Wait, you don't mean—"
    j janger "Indeed, this note from the Big Skull Boss was to give you permission to use the gangster's deadliest weapon, in its most lethal form!"
    j jdoubt "When a gangster comes sauntering down the street at you and slowly lifts their arm, what should you fear most?"
    a aalarm "A gun?"
    j jgun ". {w}. {w}."
    j jneutral "Nah, I'm talking about rhythmic hand percussion."
    a adoubt "what"
    j jgrim "I know you're an uncultured ruffian, but have you never even seen A Midsummer Night's Dream?"
    j "Gangsters are at their most dangerous when they're slowly advancing toward you while snapping, clapping, and performing Broadway choreography."
    j jdoubt "But even more dangerous than such barehanded percussion is the use of the castanets, traditionally a pair of shells bound with string."
    j "The slug is the string; its iron shell, the metal discs used in krakebs—that is, the Moroccan castanets."
    j janger "I shudder to even imagine the carnage if you got your hands on such a weapon."
    a afear "Kid, you whipped out an actual revolver like ten seconds ago."
    j janger "At any rate, your revenge plan ends here, Badmann."
    j jdoubt "I know the pain you bear must be heavy, and it's all too easy to let that pain harden into hate . . ."
    j jsurprise ". . . but that's not what your lover would have wanted, is it?"
    j "You can't heal until you learn how to forgive!"
    j jgrim "When the rest of your gang gets here, you tell them that. It's up to you to end this cycle of violence."
    j "Take care, Badmann. My work here is done."
    show mono empty
    alt "Jam departs."
    ">>>"
    a aneutral "Uh, kid?"
    a adoubt "You realize there's no actual Cranium gang coming to untie me, right?"
    a afear "Kid! Come back here!"
    show mono 14 with dissolve
    alt "A distant, rhythmic snapping comes echoing down the hall, along with three sets of footsteps."
    a "At least leave me the revolver!"
    jump endcard

label route15:
    j "What is this evidence, you ask? Well, allow me to show you."
    j jsurprise "Exhibit one: a mysterious note!"
    j jthink "Observe the handwriting. Strange, isn't it?"
    a aneutral "It does look kinda like an elementary-schooler scribbled on it with a sharpie."
    j jdoubt "No need to be so harsh, Badmann. After all, weren't you the one who wrote it?"
    a adoubt "You do know I'm a professional forger, right?"
    j jdoubt "Moving on, exhibit two: this stack of money."
    j "It's a tidy sum to have been stuffed unceremoniously under a couch."
    j jthink "Not sure exactly how much, but then, I suppose it's no mystery to you, is it . . ."
    j janger ". . . considering it's your money?"
    j jgrim "Regardless, with these two pieces of evidence, I had no trouble at all determining the exact nature of your criminal—"
    a afear "Hold up, did you say that money is mine?"
    j jalarm "Of course it's yours! If that money didn't belong to you, then how else could you have financed the—"
    a agrin "Okay, great. I confess."
    j jneutral "Wait, what?"
    a agrin "That's my money. I'm the one who did whatever it was you're about to go off about."
    j jneutral "Oh, well, alright then."
    j jdoubt "Are you sure you don't want to argue just a little more? Try and prove your innocence?"
    j jsmug "I had some really great plot twists and dramatic reversals lined up . . ."
    a aneutral "Nah, I'm good, kid."
    a adoubt "But now that we've established very clearly that the pile of money is my legitimate property, I got a proposition for you."
    a agrin "Let me go and I'll give you a hundred bucks out of that pile."
    j jgrim "That . . . sounds like bribery."
    a aneutral "I mean, you could call it that, sure."
    a agrin "But really, isn't bribery just a kind of financial transaction?"
    a "This is a free market, kid. There's nothing unsavory about a little exchange of goods and services."
    j jdoubt "I dunno about that . . ."
    j jgrim "It just doesn't seem like something that Jam, the world's greatest kid detective between the ages of 4 and 17 in the western half of Linn County, would do."
    j "I have a moral compass, you know."
    a adoubt "Alright, fine."
    a aneutral "Two hundred."
    j janger ". . . Two-fifty."
    a agrin "Deal!"
    j jsmug "Done!"
    a aneutral "Now hurry up and untie me. That money's not doing either of us any good if we get eaten by demons."
    j jdoubt "Still, I can't help but feel like there's something unresolved here . . ."
    j jthink "If you're the one responsible for the money and the escargot debacle, then how'd the horse mask get in the bathtub?"
    a aneutral "Eh, don't sweat the details, kid."
    show mono 15 with dissolve
    alt "Alexandre grins, unaware of the equine visage looming just behind him."
    a "I'm sure it's nothing you need to worry about."
    jump endcard

label secret_ending:
    j jneutral "Ha, ha, don't mind me, just passing through, doin' some detective stuff."
    a aneutral "Kid, I don't want to alarm you, but is something burning here?"
    a afear "Like, I can smell smoke and—"
    j jalarm "Everything is fine! FINE!"
    j "Slightly on fire, yes, but fine!"
    j jdoubt "All I have to do is take this fire extinguisher and—"
    a adoubt "Uh, kid, you do realize that thing's empty, right?"
    j jneutral "welp, we're gonna die"
    a afear "You can't just drop that on me without an explanation!"
    a "You said something's on fire?"
    j jalarm "Okay, yeah, right. Explanation."
    j jsurprise "So basically, I think I figured out what the crime was here, and it's arson."
    j jgrim "also i'm the arsonist, so . . ."
    a afear "Wait, what?"
    a aalarm "You lit the house on fire?"
    j jalarm "Accidentally! I accidentally started a bunch of fires in like half the rooms in this house and never put them out!"
    j jsurprise "Is it still illegal if I didn't mean to? It's not, right?"
    a adoubt "No, I'm pretty certain that's still a crime."
    show mono jterror
    ""
    j "oh god you're right"
    j jalarm "I'm . . . I'm a criminal now."
    j jdoubt "Goodbye, Jam, the world's greatest kid detective between the ages of 4 and 17 in the western half of Linn County . . ."
    j jgrim ". . . and hello Jam, the world's worst juvenile delinquent between the ages of 4 and 17 in the western half of Linn County."
    j "My career . . . My dreams . . . All up in flames."
    j jneutral "Just like us in about ten minutes, I guess."
    a aalarm "Wait, wait, hold up, kid."
    a afear "Even if you did commit arson \(which by the way it seriously sounds like you did\), you still have a future!"
    a aalarm "Also, more importantly, I still have a future and I really don't want to burn to death here, so can you please, please untie me already?"
    j jsurprise "I could have a future? Even though I'm a criminal?"
    a afear "Yeah! You're a bright kid with plenty of talents. Some of them are even useful!"
    a agrin "I'm sure you'd do fine as, I dunno, a low-level pyramid scheme administrator, or a serial noise ordinance violator."
    a "Hell, you could even be my sidekick if you wanted t—"
    j jsurprise "Really? You'd be my sidekick in crime?"
    a afear "Uh, that's not exactly—"
    j jneutral "Oh, Badmann, I can't believe I misjudged you all this time!"
    j jsmug "Don't worry; we're going to be the best crime duo the western half of Linn County's ever seen!"
    j "I'll get you untied right away! It'll only take a couple minutes!"
    $ inferno = True
    alt "The ceiling caves in partially, engulfing the room in flames."
    "C R A S H"
    j jdoubt "oooor maybe I'll just kinda drag you out of here."
    a aalarm "Whatever you're gonna do, do it fast because I think this place is about to go!"
    show mono empty
    show void_panel at basic with dissolve
    $ inferno = False
    $ location = 0
    $ refresh_location()
    pause 0.1
    hide void_panel with dissolve
    alt "Jam and Alexandre emerge from the burning house."
    ">>>"
    show mono jgrim
    j jgrim "Well, that's it for that case."
    j jneutral "In the end, the real crime was actually the friendship we forged along the way."
    a adoubt "You realize that doesn't actually make any sense, right?"
    j janger "Just shut up and let me have my moment, Badmann."
    a aneutral "Still, I can't help but feel there are some lingering questions that never got answered."
    a afear "Like, what was up with the summoning circle, and the weird letter, and why was the house abandoned in the first place?"
    a "And the demon in the lounge! Like, what the fu—"
    j jneutral "You know, not all mysteries are meant to be solved. That's my final insight as a kid detective."
    a aneutral "Yeah, I guess you're finally right for once."
    a agrin "Whatever was going on in there, it's all lost in the flames now."
    j jneutral "Exactly. So let's get a move on, yeah?"
    j jsmug "I came up with like ten crimes in the last five minutes and I'm all kinds of excited to try them out."
    j "We're gonna steal so many T. rex portraits, you wouldn't believe it."
    show mono empty
    $ inferno = False
    a "Oh boy, not this again . . ."
    show mono 16 with dissolve
    ">>>"
    jump endcard
