label raptorroom:
    show mono empty
    t "And... go go go."
    $ kickedOut = True
    n "SLAM"
    p "Gah."
    p "Guys?"
    p "Guys..."
    p "Let me back in."
    p "Hey, you can’t do this."
    p "Let me in."
    p "Oh geez."
    r "..."
    p "Hello there."
    r "..."
    p "You’re closer than I thought you would be."
    r "..."
    p "... Don’t suppose you’ll gve me a ten second start?"
    r "..."
    p "Well then. Howzabout..."
    if have_ak47:
        p "i just..."
        p "Use this?"
        $ raptorRoomAK = True
        p "..."
        r "..."
        p "Er... can I pick that up, and try again?"
        r "..."
        p "No? Okay. Well then... Howzabout..."
    if have_grenade:
        p "this?"
        $ raptorRoomGrenade = True
        p "Ha ha. Not expecting that, are we. Now I'll just do this."
        $ raptorRoomGrenadeNoPin = True
        $ raptorRoomGrenade = False
        p "Huh, the pin broke..."
        p "I guess that was older than it looked."
        p "Well. Up for catch the grenade?"
        #!!(throws grenade)"
        p "Not a catch player. Ok I get it. Not much of one myself."
        p "Well then... howzaabout..."
        $ raptorRoomGrenadeNoPin = False
    if have_wadofcash:
        p "this?"
        $ raptorRoomWadOfCash = True
        r ". . ."
        p "Yeah, I don't know what I was expecting either."
        $ raptorRoomWadOfCash = False
    p "Crud. Well, I got nothing."
    p "Kind of a docile fellow, aren’t you?"
    p "Howzabout, I just back... away slowly... and... maybe... get to the choppa."
    p "Kind of... always... wanted... to say... that."
    #!!maybe a closer raptor?
    p "Oh crap."
    show mono empty
    r "Crunch."
    jump endcard

label route01: #accussing adrian - Evidence -  print out and personal photo / Stuff - Crowbar - Find Crowbar in toilets. USe it to break open Locker. Both items are found in Reception
    p phappy "My fellow employees."
    t tsurprised "Oh. You’re back."
    p phappy "But of course. I have something most pressing-"
    t tsurprised "I honestly would have thought we would have to come get you."
    p phappy "Not at all. I am here-"
    t tsmile "I’m actually kind of impressed. Who wold have thought you would have braved your own death so willingly."
    p pshocked "Well, I am not so-"
    t tsmile "Touched even. It seems you are truly a man among men. I am sorry that we have had to fall to this route, and push such a terrible burden onto so noble a sul that-"
    p pshocked "Actually, if you would let me finish."
    t tsmile "Oh, I am sorry, my good man. Do go on."
    p phappy "I’m here to accuse Adrian of his crimes so that he can take my place."
    t tannoyed "..."
    p pstoic "..."
    t tannoyed "..."
    t tempty "I’m not sure how to feel now."
    p pevasive "Neither I am to be honest."
    a aworried "I’m sorry. Crimes? What have I done exactly?"
    p phappy "Glad you asked. Traitor to mankind. For you see-"
    h hstern "I’m sorry. Traitor to mankind? What could you have possibly found out that means that he’s betrayed all of mankind?"
    p pstoic "Well, traitor to mankind might be a bit much, I admit."
    p pevasive "Maybe a traitor to the procedures and policies of the office workplace, as documented on the staff website."
    h hstern "That’s quite a significant difference. What could he have possibly done?"
    p pshocked "Well, if you would actually let me start-"
    j jstern "Look, does this matter at all? He’s clearly just stalling so he doesn’t get eaten."
    t tempty "Feel quite sickened that I referred to him as noble to be honest."
    j jmad "This is what this man does. He’s a useless little nobody who blames others and-"
    t tempty "I feel I could actually throw up."
    j jfurious "passes off his mistakes to them. Listening to him will get us nowhere but eventually eaten because we were all too busy listening to him."
    h hstern "I don’t see the harm in it."
    j jstern "Are you kidding me? We can’t just-"
    h hstern "We have just a short time left before we have no choice but to attempt an escape. Why not let him has his last meal?"
    j jfurious "Because we’re about to be eaten."
    h hstern "Paul, what was your evidence?"
    a ahorrified "I feel I should at least get a say in this if-"
    h hstern "Quiet. The accused may not speak."
    a ashocked "But-"
    h hstern "Silence."
    h hstern "Paul, you were about to give your testimony."
    p phappy "Thank you, your honour."
    j jshocked "Oh good lord."
    p phappy"So... Take a look at this!"
    #*!!image of table with Adrian evidence*"
    t tsurprised "My god."
    h hstern "Is that-"
    p phappy "Exactly, a personal item on his desk, and personal use of the office photocopier to print off some tickets."
    p phappy "Why, if Todd hadn’t been devoured he would be-"
    t tsurprised "I can’t believe it."
    j jshocked "Oh my stars."
    a ascared "What?"
    h hstern "It is shocking, I admit."
    a aangryscared "Guys. You can’t be serious."
    j jshocked "All this time. I would never have suspected."
    a aangryscared "Seriously. This can’t be enough to-"
    t tsmile "I can’t believe he’s actually married."
    a ahorrified "What?"
    p phappy "Huh?"
    h hstern "She’s actually not bad looking either. And is this your kid?"
    a aworried "Well, yeah but-"
    j jstern "He’s adorable. What’s his name?"
    a aworried "It’s Toby."
    h hstern "Why haven’t you brought him in before?"
    a aspeechless "Well, Isabelle did suggest it, but we travel here by boat and-"
    h hstern "Oh nonsense. If the place finds a way to continue, you definitely have to bring him over. He's so sweet."
    a ablush "Oh. Thanks."
    t tempty "And all this time I could have sworn you were- well, nevermind."
    p pshocked "Erm-"
    a asmile "Well I'm sure I must have mentioned them..."
    t tupset "I suppose it sounds foolish, but i’m usually in a bit of a rush when coming into reception, so i’ve probably-"
    j jstern "Yeah, me too. Sorry, Adrian."
    h hstern "Situations like this makes you realise how we take each other for granted in the workplace."
    p pshocked "But-"
    a asmile "Oh I know. I’m just the receptionist. You just smile at me and make small talk. I’m used to it."
    t tupset "No no. We’re in the wrong here. I saw you as just another pen pusher, but you’ve got a whole life."
    t tupset "Man, i’m a shitty person. I just see people as floating heads, their individual lives easily ignored as I move past them."
    p pstoic "-this is his crime."
    t tsmile "Tell you what. When we get past all of this, i’m taking you and your family to dinner."
    a asmile "Oh you don’t have to-"
    t tsmile "Nonsense, we’ll all go."
    p pevasive "He's guilty."
    t tsmile "I know a great place. They have their own michilena star chef. Does incredibly fajitas"
    p pevasive "...of crimes."
    h hcool "Oh do you mean Tagon’s. It’s a good place. Definitely worth it."
    t tsmile "Well then I guess we all definitely have to survive then? Hey?"
    a asmile "Yeah, I guess we do. Ha."
    t tsmile "Hahaha."
    h hstern "Hahaha."
    j jstern "Hahaha."
    p phappy "Hahaha..."
    p pstoic "..."
    $ location = 10
    $ refresh_location()
    show mono empty with fade
    show mono empty with fade
    jump raptorroom

label route02: # Accussing Jenny - Evidence - Grenade - Dictaphone/Transcript / Stuff - Match/ some other firestarter - Grenade found in Security Room - Dictaphone found in JEnny's Bunk box, accessible by start a fire in the bunks, with match and fuel can. Match found in CEO Office, Fuel can found in Corridor.
    p phappy "My fellow employees."
    t tsurprised "Oh. You’re back."
    p phappy "Yes, I have indeed returned. With justice."
    t tempty "I don’t think that will help in the current man eating dinosaurs situation, "
    t tempty "but I appreciate your enthusiasm."
    p phappy "Oh it will help. Help it will indeed provide. With help I bring. In the form of justice."
    h hstern "Well now it just looks like you’re stalling."
    p phappy "Stalling with help."
    h hstern "Ok. Well look, should we just get started? Those raptors aren’t going to eat Paul themselves."
    h hcool "Well, I guess they are. That’s the whole point. You all know what I mean."
    p phappy "Behold. My evidence."
    h hstern "Evidence?"
    p phappy "You asked me to get evidence."
    h hcool  "I... No?"
    p phappy "Evidence of the crimes of another, to prove them less worthy than I to get on board the helicopter that will usher us to safety."
    h hstern "Oh right. Well, I don’t think that really matters now. I doubt anything you can really say would result in anything changing-"
    p phappy "I nominate Jenny’s crimes."
    j jmad "The hell?"
    p phappy "Jenny’s crimes are most unconsciousable, and it would do you all well to heed my words and take action from them."
    j jangry "Oh like we should be putting up with this. I was going to get you a last meal and now you accuse me of something-"
    h hstern "Jenny."
    j jangry "I mean it was just going to be something from the vending machine but he wasn’t going to have to pay."
    h hstern "Jenny."
    j jlivid "Now he tries to pass the buck off to me."
    p phappy "You are the most meatiestof us. It would increase the time it would take the raptors to consume you."
    j jshocked "..."
    h hstern "..."
    t tempty "..."
    p phappy "..."
    j jfurious "You can start running now."
    h hstern "Settle down."
    j jfurious "I am not settling-"
    h hstern "It doesn’t matter, Jenny. He’ll be dead soon, remember. Let him get this stuff out of his system."
    j jshaking "Grrr."
    h hstern "Also, the stuff in the vending machines is not safe for human consumption and him getting a stomachache may prevent him from getting a good initial panic dash in."
    j jfurious "..."
    j jstern "Fine."
    h hstern "Now, what were you saying about evidence?"
    j jangry "Seriously?"
    h hstern "I’m just curious. What do you have to show us, Paul?"
    p phappy "Yes. My evidence of Jenny’s most devious and smelly crimes!"
    p phappy "Behold!"
    t tsurprised "Jesus. Is that a grenade? Where dd you find that?"
    h hstern "And a dicataphone? Let's have a listen?"
    t tangry "I think the grenade is more pressing."
    h hstern "It has a pin in it, right? Should be safe."
    j jmad "That’s my grenade. You went through my stuff."
    t tannoyed "Why do you have a grenade?"
    j jstern "It was my father’s."
    t tangry "That does not answer the question."
    h hstern "Kind of does. Is this a conversation between me and my... client. One that we had over the phone."
    j jshocked "What? Er..."
    a asad "Wait."
    a ashocked "And this is one between me and my family. Were you listening in on us?"
    j jshocked "..."
    t tsurprised "What? Is there any for me?"
    h hstern "There’s a bunch here. It's all recordings of employees on the phone."
    t tangry "But any of me?"
    h hstern "You don’t even have a phone here."
    t tsmile "Oh, the land lines. That’s cool then."
    h hstern "Jenny? What is this?"
    p phappy "They are her crimes."
    h hstern "Shut up."
    p phappy "..."
    h hstern "Jenny?"
    j jshocked "Mr Raptorman asked me to make them. He got me to plant bugs on all the phones, and then make transcripts."
    h hstern "For just random conversations."
    j jshocked "Look, night shifts are long, and I have nothing to do. He took away my little tv, and I was bored so..."
    a aangryscared "You spied on us."
    j jshocked "Only to pass the time. It’s not like anyone really said anything too important. It was just work chatter."
    h hcool "So you don’t know..."
    h hcool "..."
    h hstern "Ok."
    a aspeechless "Ok?"
    h hstern "I’m fine with this."
    h hstern "A small violation of privacy, but nothing not worth disposing of."
    #H goes up to a shredder."
    p pangry "Hey. Don't destroy my crime evidence."
    p pangry "I worked really hard to find that."
    h hstern "I think we can all just agree that this didn’t happen."
    p pangry "Indeed. All crimes never happen if you destroy the evidence I spent hours desperately trying to-"
    a asad "I mean... I guess it’s no big deal, but Paul-"
    p pangry "SILENCE You-"
    h hstern "Things like this hardly seem important when the rest of the staff are dead. It’s not like the Park’s continuing after this anyway."
    h hstern "Honestly, I was in talks with another park. Looking to move on. No sense hiding it now."
    j jshocked "I’m sorry everyone. I was a real jerk."
    h hstern "Yeah you were. But, you’re our jerk."
    t tsmile "Yeah. And hey, you got us a grenade. That might be the handiest thing we have in the next hour."
    j jshocked "I actually kind of forgot about it in all the ruckus. It’s just a memento from my dad’s army day."
    j jshocked "I just keep it in the security cabinet with a broken gun."
    h hstern "Insanely dangerous, but i’m not complaining..."
    t tempty "And Paul just found it along with the dictaphone?"
    j jshocked "Well that would have been in my bunk chest, but yeah I guess.."
    t tangry "Wait, did you say your bunk locker?"
    p phappy "That is where the evidence was recovered, yes."
    t tangry "Have you been going through our stuff?"
    p pevasive "..."
    $ location = 10
    $ refresh_location()
    show mono empty with fade
    show mono empty with fade
    jump raptorroom

label route03: # Accussing Helen - Evidence - Research Journal/Raptor Claw / Stuff - Research Journal found under chair in Lab (staff room) - Raptor Claw found by using security card on containment lock. Card found in CEO office
    p phappy "My fellow Americans."
    h hstern "Actually, i’m Canadian."
    t tempty "Me too."
    a asad "British."
    j jstern "I’m actually from Hawaii."
    p phappy "That doesn't count."
    j jmad "The hell you say!"
    p phappy "Anyway, I bring to you, in this most dire of times, evidence. "
    p phappy "Evidence that supports my case and makes it clear that one among us is a traitor, and should be totally thrown out of the airlock first."
    j jstern "What on Earth are you talking about?"
    p phappy "I mean, I guess that’s kind of what all this is."
    p phappy "Though it totally wasn’t my intention when it all started."
    p phappy "It was more just about finding reasons why someone should be thrown out to be eaten by Velociraptors."
    p pstoic "And why that someone shouldn’t be me."
    p pevasive "That was the whole premise of this entire game."
    p pevasive "I mean escapade."
    h hstern "I think you’re getting off track."
    p phappy "Or perhaps it is the only track I should be on."
    p phappy "Maybe this is my life now. Endlessly finding ways to stay on track, the track of accusing other people of crimes that they may or may not have committed. "
    p phappy "All in the hopes of saving myself. A person who may not be worthy of being saved."
    t tempty "Well if you’re just going to admi it..."
    p phappy "I admit nothing. Instead, I provide evidence."
    h hstern "What?"
    p phappy "EVIDENCE."
    h hstern "Of What?"
    p phappy "Huh?"
    h hstern "Evidence that proves what?"
    p phappy "Oh right, that Helen is secretly evil and was conspiring with a rival corproation to take this place down."
    p phappy "Huh? That actually seems like a pretty good find."
    j jshocked "What’s this?"
    a ahorrified "Huh? These appear to be research notes on Velociraptor Reproduction Analysis. "
    a ascared "It’s a method of giving asexual dinosaurs the ability to reproduce, and how to increase the frequency."
    h hcool "Erm..."
    t tupset "Jesus."
    a ahorrified "With this method, reproduction rates would increase from zero to three raptors a day within the space of about three weeks. "
    t tangry "Wouldn’t that overrun the park?"
    j jshocked "We were having problems keeping the ten we have at the moment contained"
    j jshocked "I mean, it was doable, but there were daily issues."
    a areallyshocked "If this happened, it would have been so much worse than the current situation."
    h hangry "..."
    h hstern "Well yes, but the research was entirely hypothetical. It’s not like I actually planned to go through with it-"
    a aworriedangry "And within the journal is a transcript of you speaking with Hammond Industries CEO."
    a aworriedangry "Where he asks you to sabotage the park by introducing the changes in the raptors DNA via their water supply."
    p phappy "I found it under a chair!"
    t tannoyed "Helen. This. This is horrible."
    t tannoyed "Were you really going to put us all at risk like this?"
    h hcool "...No?"
    h hstern "Not necessarily. I mean, in order to even get away with something like this..."
    h hstern "I would have had to do it at a time when there was a low staff turnout on the island."
    h hstern "People would notice far too quickly if I tried to sabotage the water supply. I at least had to do it when the Environmental officer was on leave."
    a aworried "Well I suppose..."
    h hcool "In four days time."
    a aworriedangryshocked "..."
    h hstern "Look, it’s not as bad as it sounds."
    j jmad "Why would you do this? Why would you risk getting us all killed like this?"
    h hstern "You wouldn’t have gotten killed. I don’t want anyone to die. The jump in reproduction rates would have been noticed within the first week."
    h hstern "We would respond by disabling the raptors, enacting a castration protocol for the males."
    h hstern "Including the baby ones. The long terms effects of the issue would be resolved within the year."
    h hstern "The point was is that I would fix the issue and get commended for doing so. "
    h hstern "That way I'd finally actually get noticed and not be passed up for promotion again."
    t tangry "This was all for a promotion?"
    h hstern "Not all for a promotion.I didn’t even do anything in the end. It was just a plan I was considering."
    p phappy "But, she was talking to the CEO of-"
    h hstern "Yes Exactly. Our CEO found my research papers. He cotton onto it."
    h hstern "It's hard in the research world. You don't get noticed unless you do something extreme..."
    h hstern "We actually just had a talk yesterday about it. Got the entre thing out in the open."
    h hstern "He even apologised to me. Realised how stressed I had been."
    h hcool "He was such a sweet man." 
    h hangry "I just wish this moron hadn’t gotten him eaten."
    p phappy "But-"
    t tempty "I guess we don’t consider how stressful it is for those of you in the Research sector."
    j jshocked "Yeah just because it looks like you have the cushy science job that you’re getting by just fine."
    j jshocked "You must have all sorts of stresses that we working plebs don’t have to deal with."
    h hstern "Oh come on guys. I’m not some elite pretentious jerk, looking to screw everyone else over just to get a promotion."
    h hstern "I have to clock in at 10am the same as the rest of you."
    a asad "My shift starts at nine."
    j jstern "I start at six."
    t tupset "I’m on call 24/7."
    h hstern "Even so, we’re all just working for a paycheck. I was even going to use my bonus to spring for a big dinner for all the staff."
    h hstern "It’s a shame  it won’t happen now."
    p pstoic "I think that-"
    j jshocked "You were going to do that for us?"
    h hstern "Yeah, fanciest place on the port. I was really looking forward to announcing it as well."
    p pevasive "We may be missing the point-"
    t tsmile "Hey you know what, why don't we go there now?"
    h hcool "Now? But, the raptors."
    t tsmile "Once we get off this island. When we survive this, you can take us out to dinner."
    h hcool"Tony..."
    h hstern "Everyone..."
    h hstern "Thank you."
    h hstern "I don’t deserve to have co-workers like you."
    a ahappy "You sure don’t."
    j jstern "Come on. Bring it in guys."
    p pstoic "But the transcript-"
    a ahappy"Let’s go out there, and get to that helicopter."
    p pstoic "Is anyone listening..."
    $ location = 10
    $ refresh_location()
    show mono empty with fade
    show mono empty with fade
    jump raptorroom

label route04: # Accussing Tony - Evidence - Assassin Contract/Wad of Cash / Stuff - Hammer Wad of cash found in Tony's bunk. Contract found in CEO office globe by smashing globe with hammer. HAmmer found under teddy bear in bunks
    j jstern "Oh good. You’re here."
    p pshocked "Ok. Everyone. You have to listen to me."
    h hcool "Ah, the desperate bargaining."
    h hstern "I was wondering when he would start."
    p pshocked "No, this isn’t just- I mean. It’s not as simple as-"
    t tempty "..."
    p pshocked " Oh geez."
    a asad "Calm down, Paul. I know it’s a lot to take in but-"
    p pangry "Oh shut up, Adrian. No one likes you."
    a asad "I..."
    a ahorrified "Oh."
    t tsmile "Don’t listen to him, Adrian. He’s just panicked because of what we’re asking him to do."
    a asad "Really?"
    t tsmile "Of course. Why, I’d kill to just sit down and have a beer with you sometime. We should do so after this."
    p phappy "..."
    a ahappy "Thanks, man. I guess my ego’s not the best at handling that kind of thing."
    t tsmile "Don’t sweat it. I’d hate for you to get all cut to pieces about this."
    p pstoic "..."
    a ahappy "Heh. I’ve been told I get a little imposter syndrome at times. I know  it’s not healthy, but it’s part of my life I guess."
    t tsmile "Hey, it's nothing to get blown up into little chunks about."
    t tsmile "It’s not like someone’s going to seal you inside a concrete coffin just because you get nervous at times."
    p pevasive "..."
    a ahappy "Heh. Thanks man."
    t tsmile "Don’t sweat it."
    p pshocked "He’s a murderer."
    h hstern "What?"
    j jstern "What?"
    t tempty "..."
    a ashocked "What? No, i’m not."
    p pangry "No. Not you. Tony."
    t tupset "Hey, what I did I did for my country. I served. It doesn’t count."
    p pshocked "No. I mean...he’s a hitman. Look at this."
    h hstern "Contract of Assassination. This contract is an agreeded upon set of of principals for which the sum of $200,000 shall be exchanged..."
    h hstern "...if the target of the contract's life ends within the agreed upon date range..."
    t tupset "Erm..."
    p pshocked "I found it when looking around."
    p pshocked "Though I don't get why it was in Todd's office."
    p pevasive "Probably someone's bad planning."
    h hstern "This contract stipulates that Tony Flyover shall receive the agreed upon amount in the wake of the death of Cretanious Corner’s CEO Todd Raptorman."
    j jstern "What is this? Some kind of joke."
    t tannoyed "What... Er...Yeah."
    t tsmile "Yeah, it’s a joke. Me and Paul here are just having a laugh at you. But he got the timing wrong."
    t tsmile "Didn’t you, Paul? I wouldn’t want you to trip over into a waste disposal unit and get yourself hurt."
    a asad "..."
    h hstern "..."
    j jshocked "..."
    j jstern "Well that sounded like an obviously veiled threat to me."
    t tempty "Really? Usually it goes right over people’s heads."
    t tempty "Well. Can’t blame a guy for continuing to do what worked so well before."
    h hstern "So. You mean..."
    t tsmile "Yes. I am a contract killer. And I was hired to kill your boss."
    t tannoyed "Not that that matters now."
    j jshocked "How could this be-"
    t tempty "Huh, you know. You leave the army. No one will take you on for work. You end up being homeless. End up doing a few jobs for the mob."
    t tsmile "End up doing them really well, and they give you all sorts of roles to do."
    t tsmile "Not long before you end up going back to the government for work."
    t tsmile "Helps that I actually am a helicopter pilot. Lets me go all over the place."
    a ashocked "So you were going to-"
    t tannoyed "Kill the CEO, yes. Turns out his competitors hate that he got out of paying settlement costs for obvious copyright infringement."
    t tangry "Again. Not thast any of it matters."
    h hstern "..." #reading the contract
    t tangry "Though, I suppose that now you all know..."
    p pstoic "..."
    j jshocked "..."
    a areallyshocked "..."
    h hstern "..." #reading
    h hstern "As far as i’m concerned, this changes nothing." #now not reading
    t tempty "What?"
    p pshocked "What?"
    h hstern "I am saying this is not reason enough to swap you out with Tony."
    p pstoic "But he’s a paid killer."
    h hstern "Tony. Were there  contracts out on any of us besides the CEO?"
    t tempty "..."
    t tempty "There were not."
    h hstern "And would death by raptor still get you paid?"
    t tempty "..."
    t tsurprised "It would. I can claim it was a planned accident."
    h hstern "So this doesn’t really change anything fo us."
    p phappy "But, but he’s a killer A murderer. Who knows when he’lll plan to just off one of us-"
    t tupset "Hey. I’m a professional. You only die by my hand if you’re a contract, or if you’re in my way."
    t tupset "And you’re looking very much like an obstruction, boy."
    p pstoic "..."
    h hstern "It’s irrelevant. And it doesn’t change the most important fact about all of this."
    t tupset "Yeah, and what’s that?"
    h hstern "That you’re the only one that can pilot the helicopter. We can’t leave you behind."
    t tsurprised "..."
    p phappy "..."
    t tsmile "Oh right."
    p phappy "Yeah, that makes total sense."
    t tsmile "Can't believe I didn't start with that."
    p phappy "Yeah. Don’t know what I was thinking. Sorry."
    t tsmile "Don’t worry about it. You’re just not thinking straight. Happens to anyone in a situation like this."
    p phappy "Yeah..."
    h hstern "Anyway, if we’ve all had enough shenanigans. Let’s continue with the escape plan with Paul being used as bait."
    t tsmile "Okay..."
    p phappy "Yeah okay."
    p phappy "..."
    p pshocked "Hey wait-"
    $ location = 10
    $ refresh_location()
    show mono empty with fade
    show mono empty with fade
    jump raptorroom

label route05: # faking evidence to accuse Adrian - Evidence - Fake Transcript/ Fake ID card / Stuff - Plain paper/ Plain ID card - Plain paper found in reception, ID found in Lab, security puzzle completed in security room
    a asad "And that’s why i’m thinking we should be nicer to the guy. If he is going to die today, then the least we could do is not be dicks about it and-"
    p phappy "Yoohoo. I have here evidence to present to all of you."
    a asmile "Ah Paul. It is good to see you. Thank you for coming back-"
    p phappy "Shut up, Adrian."
    a ascared "I- excuse me."
    p phappy "Oh i’m sorry. Was I unclear? Stop. Making. Noises."
    a ascared "Well there’s no need to be so-"
    p phappy "I am onto your evil scheme. I have discovered all the proof I require."
    a ashocked "Wh- what is ths? What are you going on about."
    p phappy "Here. I present to you all.... Evidence. Evidence that Adrian is the cause of our current situation."
    a areallyshocked "What?"
    h hstern "Seriously?"
    p phappy "Please do not question how I came upon this evidence in such a short period of time, and instead question Adrian’s true motives."
    p phappy "For he is the one who attempted to hide this evidence, and I am the one who attempted to find it."
    p phappy "And er... did."
    h hstern "What are you babbling about? Give that here."
    a ashocked "What is he talking about?"
    h hstern "This..."
    h hstern "These are the access logs for the raptor exhibit at the time of their escape."
    h hstern "It shows someone intentionally unlocked the exhibit at the time the CEO and the others were in the area. "
    h hstern "ID: 4025202 four zero two five two zero two... whose is that?"
    a aworriedshocked "Erm... that’s mine. But I didn’t. I couldn’t have- wouldn’t have. I mean..."
    p phappy "I overheard a conversation between Adrian and Todd the other day. Adrian was annoyed that Todd didn’t approve his bonus for this year."
    p phappy "Said he hadn’t been working long enough."
    h hstern "Erm yeah. Sure-"
    h hstern "Geez, this shows Adrian disabling the security locks and taking out the defence grid."
    a aworriedshocked "No. It’s wrong. I mean, I know it looks like-"
    t tupset "Shut up. Is this genuine?"
    h hstern "These are how the access logs show up on the system, and Paul wouldn’t have access to modify that system. "
    h hstern "Only the systems administrator and the CEO would have that. You could view it but that’s about it."
    p phappy "I saved it as a pdf, then copied it to Word to print out."
    h hstern "It definitely looks accurate, and makes it clear that Adrian’s responsible."
    a aworriedshocked "But... i’m not. I seriously don’t know what this is. I’ve never seen-"
    j jstern "Never seen, huh?"
    a ascared "What?"
    j jangry "The Reception would have access to these systems as a security precaution. "
    j jangry "Adrian can theoretically activate and deactivate defences at any time."
    j jangry "Since he’s most likely the first person to notice a dinosaur coming up the main entrance."
    p phappy "That is exactly what i was thinking as well."
    t tempty "I would have thought he'd just be able to activate it. Shouldn’t a manager or something be the one to deactivate it?"
    j jstern "It’s not a bank. He’d need to be able to turn these things on and off just in case someone came running up to the doors after the force field was up."
    j jstern "Geez, Adrian. Why?"
    a ascared "It's not... I- I wouldn't-"
    h hstern "So it’s entirely feasible he could do this."
    a ascared "But-"
    p phappy "I just thought you should all know what he did before I died."
    p phappy "I suppose we should get on with my final moments."
    p phappy "I hope you all make it out alive."
    h hstern "Wait."
    a ashocked "Oh no."
    h hstern "We need to reconsider things."
    t tupset "Yeah. We were doing this to Paul because we thought he was responsible."
    j jstern "But he was responsible."
    j jstern"We saw it on the cameras that he was the one that deactivated everything by accident."
    p phappy "..."
    p phappy "(oh right)"
    h hstern "Yes, but he did it by accident at the same time Adrian apparently did it intentionally."
    a areallyshocked "I did no such thing. You guys- I think someone may be trying to frame me."
    a asad "Though who..."
    h hstern "Look, we’re nearly out of time."
    h hstern "And, as far as i’m concerned, either one of you is suitable to the task of distracting raptors through sheer panic."
    a ashocked "You don’t mean-"
    j jstern "Wait."
    j jstern "We don’t know if he really did this."
    j jstern "What if someone used his access in order to do this as him?"
    h hstern "Well presumably such a person would keep themselves safe and be one of the remaining survivors."
    h hstern "Which basically means that it’s still one of us, and we would need to spend time determining who within the next minute or two."
    j jshocked "..."
    j jshocked "Objection withdrawn."
    a areallyshocked "What?"
    j jshocked "I ain’t wasting time trying to figure that out. Let’s just have them felip a coin or something."
    p pshocked "What?"
    a ashocked "Seriously?"
    j jstern "Yeah, that works. One definitely helped cause this by accident, and one may have intentionally done it."
    j jstern "Either is pretty bad. Let’s flip a coin and decide that way."
    h hstern "Seems reasonable."
    p phappy "Wait-"
    t tempty "Yeah, let’s go with that."
    a ascared "I don’t think."
    h hstern "It doesn’t matter what you think. It’s three against two. Anyone got a coin?"
    a ascared "I mean I do but-"
    h hstern "Thank you."
    h hstern "So. Paul. Heads or Tails?"
    show mono black with dissolve
    p "It’s nice to know things work out well in the end."
    p "You clock in everyday. You work hard."
    p "You get noticed by your boss and you’re appreciated for your efforts."
    show mono helicoptor with dissolve
    p "Life goes by nicely. "
    p "Sure i’ll have to get a new job now."
    p "And I don’t have anyone left to give me a reference from my old job."
    p "But it’s sure to make an interesting story in the next interview."
    p "All it requires is a way to bring it up organically."
    p "Oh, I could also mention I got to ride on a helicopter."
    p "That’ll make me stand out."
    show mono birdseye with dissolve
    p "Yep. Sure is a good day."
    jump endcard

label route06: # any combination of incorrect evidence
    p phappy "Greetings all. I have returned."
    j jstern "‘bout damn time. We were just about to come fish you out of whatever cupboard you had hidden yourself in."
    p phappy "I- wait, was that an option?"
    j jstern "..."
    j jshocked "I mean, technically, yes. I suppose."
    j jstern "Couldn’t we all just hide in cupboards until this goes away?"
    h hstern "The forcefield will break down shortly. After that, it’s just a matter of the raptors entering the building and sniffing us out."
    h hstern "It’s possible they’ll get bored and wander away from the building, but then we’ll be trapped here indefinitely."
    t tannoyed "It’s not like anyone knows to come rescue us."
    t tannoyed "People probably won't be getting suspicious there’s something wrong for at least four days."
    h hstern "And at any point the raptors could just burst in here and start chewing down on us."
    h hstern "Better we do it this way, than get eaten in our sleep."
    j jstern "Okay okay. So no, it’s not an option?"
    p phappy "Duh. Of course it’s not an option."
    j jangry "Shut it, you."
    a ahorrified "So I guess we get started then?"
    p phappy "Actually, before we do that. I have some evidence to present."
    p phappy "Evidence I dare say you should find most illuminating."
    t tempty "Evidence? For what?"
    p phappy "Evidence that shows one of us is not worthy for survival of course."
    p phappy "At least, less worthy than I."
    a asad "Than me."
    p phappy "Exactly."
    a asad "No no. ‘Less worthy than ‘me’’. You use the object pronoun, not the subject pronoun."
    p phappy "Exactly."
    a asad "..."
    h hstern "What is this evidence?"
    t tupset "Yeah, let’s get this over with quickly. I get the feeling this is going nowhere."
    p phappy "Very well."
    p phappy "Behold."
    p phappy "My evidence."
    j jshocked "Oh my word."
    h hcool "Interesting."
    t tannoyed "This..."
    t tupset "Is absolutely meaningless."
    p phappy "It is?"
    t tangry "Yes of course."
    t tangry "These two items, which are so meaningless in their relationship I will now only refer to them ambiguously,"
    t tangry "have no connection to each other whatsoever."
    p phappy "Really?"
    p phappy "But what if I arrange them in this configuration?"
    t tsurprised "I... I mean that’s actually really good."
    j jshocked "It’s beautiful."
    h hcool "What have I been doing with my life before this moment?"
    t tempty "But it still doesn’t really mean anything."
    t tannoyed "The two pieces of evidence, which are both still admittedly wonderful but also still unworthy of being labeled,"
    t tannoyed "do not have any connection to each other."
    t tempty "Sorry, Paul, but I think you just weren’t paying enough attention."
    p phappy "D’aawwww. I guess i’ll have to try again."
    t tempty "I guess so."
    h hstern "No. No he won’t."
    h hstern "Times up. We have to go."
    h hstern "Sorry, Paul. But your  attempt to pass the blame onto someone else has been fruitless."
    p phappy "Aww, but I tried really hard."
    h hstern "I know you did, sweetie."
    p phappy "..."
    h hstern "..."
    t tempty "..."
    h hstern "Okay, people. Let’s get a move on. Those raptors aren’t going to eat themselves."
    h hstern "We in R&D had to work real hard to prevent that happening."
    h hstern "In retrospect it wasn’t worth it."
    j jstern "Hey..."
    j jshocked "Do you suppose we could take this evidence with us?"
    h hstern "..."
    h hstern "It was pretty nice evidence."
    $ location = 10
    $ refresh_location()
    show mono empty with fade
    show mono empty with fade
    jump raptorroom

label route07: # brain broken due to puzzle
    $ route = _("9/16: It wasn't that hard...")
    $ persistent.end_09 = True
    p phappy "So if this bit goes here and that bit goes there."
    p phappy "And that bit goes there and this bit goes here."
    p phappy "Then it makes sense that this bit doesn’t belong here."
    p phappy "And that piece does belong there."
    p phappy "So it’s pretty clear by this point..."
    p phappy "That this puzzle box is secretly more than a puzzle box."
    p phappy "It is actual a metaphor for all of everything in the universe,"
    p phappy "The box emcompasses all of me."
    p phappy "And I am all of the universe."
    p phappy "There are probably even little versions of the puzzle box within the puzzle box."
    p phappy "Since, by definition, something that emcompasses everything should also contain itself."
    p phappy "And by that logic - why is my brain copper tasting."
    p phappy "..."
    p pbrainmelt "It’s so delicious."
    show mono empty
    p "..."
    p "..."
    r rrap "SOME TIME LATER"
    t tempty "Found him. He’s here."
    t tsurprised "Holy crap."
    t tangry "I think he’s dead."
    a areallyshocked "Zounds!"
    h hstern "Let me see."
    h hstern "I have a PhD, and am therefore definitely a doctor."
    h hstern "..."
    h hstern "Looks like he is."
    h hstern "Some kind of anueriysim."
    h hstern "anueroism"
    h hcool "an-nue-ro-ism"
    t tempty "Aneurysm"
    h hangry "That’s what I said."
    h hstern "His head has basically exploded."
    h hstern "Possibly, from too much thinking."
    j jshocked "I suppose we did put a lot on his plate."
    j jshocked "Maybe we were too hard on the fellow."
    h hstern "Possibly..."
    t tannoyed "More importantly though, what are we going to do now?"
    t tempty "Do we choose between one of us who should go out there first."
    h hstern "Actually, I have a better idea."
    r rrap "MORE TIME LATER!"
    t tsurprised "I just don’t get why you guys have a catapult on the roof."
    a asad "I always questioned it but someone always said-"
    h hstern "Shut it, Adrian."
    h hstern "There’s no time to explain."
    h hstern "There is a remote controlled catapult installed on the roof. The CEO wanted it, and he’s rich, so it got made."
    h hstern "Here’s the plan."
    h hstern "We’ve loaded up Paul’s body. Now we all go back downstairs, get to the force field, activate the catapult, "
    h hstern "Wait for the raptors to take the bait, then turn off the forcefield and run. Everyone got it?"
    a ahorrified "So we’re using his body."
    h hstern "As bait still, yes."
    h hstern "Him still being alive wasn’t really necessary."
    h hstern "Just being made of meat and able to covered a suitable distance."
    h hstern "In fact, this is even better, as we’ll be able to pinpoint a general landing area far enough away for the corpse to land."
    h hstern "Much better than Paul barely making it out of the front door."
    t tsmile "I guess it was a good job he did die then. He’s really raised our chances of success."
    a asmile "I knew Paul wouldn't let us down in the end."
    j jangry "Why did you make me haul the body up the stairs?"
    j jshocked "He was so stiff."
    h hstern "Right, so we’re all good to go. Calculations are set. No test shot so we’ll have to hope for the best."
    h hstern "Everyone get downstairs and be prepared for the sprint of your life."
    j jshocked "Still warm."
    t tsmile "Come on Jenny. Time’s a wasting."
    #!!catapult ending
    jump endcard

label grenadeend: # checking the grenade
    jump endcard

